# Generated by Django 6.0.4 on 2026-04-25 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('section', models.CharField(blank=True, max_length=255)),
                ('description_heading', models.TextField(blank=True)),
                ('enrollment_code', models.CharField(blank=True, max_length=50)),
                ('course_state', models.CharField(default='ACTIVE', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='IN_PROGRESS', max_length=50)),
                ('courses_synced', models.IntegerField(default=0)),
                ('students_synced', models.IntegerField(default=0)),
                ('assignments_synced', models.IntegerField(default=0)),
                ('submissions_synced', models.IntegerField(default=0)),
                ('errors', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('work_type', models.CharField(choices=[('ASSIGNMENT', 'Assignment'), ('SHORT_ANSWER_QUESTION', 'Short Answer Question'), ('MULTIPLE_CHOICE_QUESTION', 'Multiple Choice Question')], max_length=50)),
                ('max_points', models.FloatField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('topic', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(default='PUBLISHED', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.course')),
            ],
            options={
                'ordering': ['due_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_id', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=255)),
                ('profile_photo', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.course')),
            ],
            options={
                'ordering': ['full_name'],
                'unique_together': {('google_id', 'course')},
            },
        ),
        migrations.CreateModel(
            name='StudentMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_rate', models.FloatField(default=0.0)),
                ('average_score', models.FloatField(blank=True, null=True)),
                ('on_time_rate', models.FloatField(default=0.0)),
                ('late_submissions', models.IntegerField(default=0)),
                ('missing_submissions', models.IntegerField(default=0)),
                ('category', models.CharField(blank=True, choices=[('FOCUS', 'Needs Focus'), ('PUSH', 'Needs Push'), ('PRAISE', 'Deserves Praise')], max_length=10, null=True)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_metrics', to='core.course')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='core.student')),
            ],
            options={
                'verbose_name_plural': 'Student Metrics',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_id', models.CharField(max_length=255, unique=True)),
                ('state', models.CharField(choices=[('NEW', 'New'), ('CREATED', 'Created'), ('TURNED_IN', 'Turned In'), ('RETURNED', 'Returned'), ('RECLAIMED_BY_STUDENT', 'Reclaimed by Student')], max_length=50)),
                ('late', models.BooleanField(default=False)),
                ('assigned_grade', models.FloatField(blank=True, null=True)),
                ('draft_grade', models.FloatField(blank=True, null=True)),
                ('creation_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.student')),
            ],
            options={
                'ordering': ['-update_time'],
                'unique_together': {('assignment', 'student')},
            },
        ),
    ]
