# Generated by Django 5.2.13 on 2026-04-25 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cohort_course_cohort'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='closed_date',
            field=models.DateField(blank=True, help_text='Date when cohort was closed', null=True),
        ),
        migrations.AddField(
            model_name='cohort',
            name='data_archived',
            field=models.BooleanField(default=False, help_text='Data has been archived/saved'),
        ),
        migrations.AddField(
            model_name='cohort',
            name='is_closed',
            field=models.BooleanField(default=False, help_text='Cohort is permanently closed'),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_google_id', models.CharField(max_length=255)),
                ('student_name', models.CharField(max_length=255)),
                ('student_email', models.EmailField(max_length=254)),
                ('certificate_type', models.CharField(choices=[('COURSE', 'Course Completion'), ('COHORT', 'Cohort Completion')], default='COHORT', max_length=50)),
                ('issued_date', models.DateField()),
                ('completion_percentage', models.FloatField(help_text='Overall completion percentage')),
                ('average_grade', models.FloatField(blank=True, help_text='Average grade across assignments', null=True)),
                ('certificate_url', models.URLField(blank=True, help_text='URL to certificate file')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='core.cohort')),
                ('course', models.ForeignKey(blank=True, help_text='Specific course (if certificate is for single course)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='core.course')),
            ],
            options={
                'ordering': ['-issued_date'],
                'unique_together': {('student_google_id', 'cohort', 'course')},
            },
        ),
        migrations.CreateModel(
            name='CohortEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_google_id', models.CharField(help_text="Student's Google ID", max_length=255)),
                ('student_name', models.CharField(max_length=255)),
                ('student_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('ENROLLED', 'Enrolled'), ('COMPLETED', 'Completed'), ('DROPPED', 'Dropped'), ('IN_PROGRESS', 'In Progress')], default='ENROLLED', max_length=20)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.cohort')),
            ],
            options={
                'verbose_name_plural': 'Cohort Enrollments',
                'ordering': ['cohort', 'student_name'],
                'unique_together': {('student_google_id', 'cohort')},
            },
        ),
    ]
