# Generated by Django 5.2.13 on 2026-04-28 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cohort_closed_date_cohort_data_archived_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_email', models.EmailField(max_length=254)),
                ('student_name', models.CharField(max_length=255)),
                ('student_unique_id', models.CharField(blank=True, help_text='D4WEE unique ID', max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField(help_text='Date of attendance')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent')], default='PRESENT', max_length=10)),
                ('week_number', models.IntegerField(help_text='Week number (1-12)')),
                ('courses_enrolled', models.TextField(blank=True, help_text='Comma-separated list of enrolled courses')),
                ('learnings', models.TextField(blank=True, help_text='What have you learned over the past week?')),
                ('assignments_completed', models.CharField(blank=True, help_text='How many assignments completed this week?', max_length=255)),
                ('challenges', models.TextField(blank=True, help_text='Any challenges or roadblocks?')),
                ('timestamp', models.DateTimeField(help_text='When the form was submitted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='core.cohort')),
            ],
            options={
                'ordering': ['-date', 'student_name'],
                'indexes': [models.Index(fields=['date', 'status'], name='core_attend_date_07f009_idx'), models.Index(fields=['week_number', 'status'], name='core_attend_week_nu_3eb0ad_idx'), models.Index(fields=['student_email'], name='core_attend_student_c47fdc_idx')],
            },
        ),
    ]
