# Generated by Django 5.2.13 on 2026-04-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_attendancerecord'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='attendancerecord',
            name='core_attend_date_07f009_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendancerecord',
            name='core_attend_week_nu_3eb0ad_idx',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='status',
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['date'], name='core_attend_date_4e3795_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['week_number'], name='core_attend_week_nu_e63e8b_idx'),
        ),
    ]
