# Generated by Django 5.2.13 on 2026-05-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_attendancerecord_core_attend_date_07f009_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmetrics',
            name='assignment_average',
            field=models.FloatField(blank=True, help_text='Average score for assignments/quizzes only (excludes pre/post tests)', null=True),
        ),
        migrations.AddField(
            model_name='studentmetrics',
            name='improvement_rate',
            field=models.FloatField(blank=True, help_text='Percentage improvement from pre-test to post-test', null=True),
        ),
        migrations.AddField(
            model_name='studentmetrics',
            name='post_test_score',
            field=models.FloatField(blank=True, help_text='Average score on post-tests', null=True),
        ),
        migrations.AddField(
            model_name='studentmetrics',
            name='pre_test_score',
            field=models.FloatField(blank=True, help_text='Average score on pre-tests', null=True),
        ),
    ]
