# Generated by Django 5.2.13 on 2026-05-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_studentmetrics_assignment_average_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmetrics',
            name='eligibility_notes',
            field=models.TextField(blank=True, help_text='Reasons for eligibility or ineligibility'),
        ),
        migrations.AddField(
            model_name='studentmetrics',
            name='is_certificate_eligible',
            field=models.BooleanField(default=False, help_text='Whether student meets all certificate criteria'),
        ),
        migrations.AddField(
            model_name='studentmetrics',
            name='post_test_attempted',
            field=models.BooleanField(default=False, help_text='Whether post-test was attempted'),
        ),
        migrations.AddField(
            model_name='studentmetrics',
            name='pre_test_attempted',
            field=models.BooleanField(default=False, help_text='Whether pre-test was attempted'),
        ),
        migrations.AddField(
            model_name='studentmetrics',
            name='session_attendance_rate',
            field=models.FloatField(default=0.0, help_text='Overall session attendance percentage'),
        ),
        migrations.AddField(
            model_name='studentmetrics',
            name='weekly_call_attendance_rate',
            field=models.FloatField(default=0.0, help_text='Weekly call attendance percentage'),
        ),
    ]
