# Generated by Django 5.2.13 on 2026-05-19 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_certificate_eligibility_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmetrics',
            name='eligibility_notes',
        ),
        migrations.RemoveField(
            model_name='studentmetrics',
            name='is_certificate_eligible',
        ),
    ]
