# Generated by Django 5.2.13 on 2026-05-19 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_certificate_eligibility_db_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cohort',
            name='data_archived',
        ),
        migrations.RemoveField(
            model_name='cohort',
            name='is_active',
        ),
    ]
