# Generated by Django 5.2.13 on 2026-05-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_cohort_is_active_and_data_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='google_id',
            field=models.CharField(blank=True, help_text='Google ID matched from Student records', max_length=255),
        ),
    ]
