name: d4wee-dashboard
region: nyc

services:
  - name: web
    github:
      branch: main
      deploy_on_push: true
      repo: codeforpakistan/d4wee
    build_command: |
      python -m pip install -r requirements.txt
      python manage.py collectstatic --noinput
    run_command: gunicorn d4wee.wsgi:application --bind 0.0.0.0:$PORT
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080
    routes:
      - path: /
    envs:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "d4wee.codeforpakistan.org,${APP_DOMAIN}"
      - key: SECRET_KEY
        type: SECRET
        value: "CHANGE_ME_AFTER_DEPLOYMENT"
      - key: DATABASE_URL
        value: "${db.DATABASE_URL}"
      - key: GOOGLE_OAUTH2_CLIENT_ID
        type: SECRET
        value: "CHANGE_ME_AFTER_DEPLOYMENT"
      - key: GOOGLE_OAUTH2_CLIENT_SECRET
        type: SECRET
        value: "CHANGE_ME_AFTER_DEPLOYMENT"

databases:
  - name: db
    engine: PG
    version: "16"
    production: false
    cluster_name: d4wee-db

domains:
  - domain: d4wee.codeforpakistan.org
    type: PRIMARY
