# Generated by Django 5.2.13 on 2026-05-19 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='UPCOMING', max_length=20)),
                ('is_open_for_registration', models.BooleanField(default=False, help_text='Students can request to join')),
                ('max_students', models.IntegerField(blank=True, help_text='Maximum number of students (optional)', null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Course code (e.g., PY101)', max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('google_id', models.CharField(blank=True, help_text='Google Classroom course ID (if exists)', max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('is_visible', models.BooleanField(default=True, help_text='Show in student catalog')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('work_type', models.CharField(choices=[('ASSIGNMENT', 'Assignment'), ('SHORT_ANSWER_QUESTION', 'Short Answer Question'), ('MULTIPLE_CHOICE_QUESTION', 'Multiple Choice Question')], help_text='Type from Google Classroom API', max_length=50)),
                ('assignment_type', models.CharField(choices=[('PRE_TEST', 'Pre-Test'), ('POST_TEST', 'Post-Test'), ('ASSIGNMENT', 'Assignment'), ('QUIZ', 'Quiz')], default='ASSIGNMENT', help_text='Explicit categorization for tracking', max_length=20)),
                ('max_points', models.FloatField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('topic', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(default='PUBLISHED', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='app.course')),
            ],
            options={
                'ordering': ['due_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('DROPPED', 'Dropped')], default='PENDING', max_length=20)),
                ('requested_date', models.DateTimeField(auto_now_add=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_registrations', to=settings.AUTH_USER_MODEL)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='app.cohort')),
            ],
            options={
                'verbose_name_plural': 'Registrations',
                'ordering': ['-requested_date'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(choices=[('COURSE', 'Course Completion'), ('COHORT', 'Cohort Completion')], default='COHORT', max_length=20)),
                ('issued_date', models.DateField()),
                ('completion_percentage', models.FloatField(help_text='Overall completion percentage')),
                ('average_grade', models.FloatField(blank=True, help_text='Average grade', null=True)),
                ('certificate_url', models.URLField(blank=True, help_text='URL to certificate file')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, help_text='Specific course (for course certificates)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='app.course')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='app.registration')),
            ],
            options={
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_id', models.CharField(help_text='Google ID from OAuth', max_length=255, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('profile_photo', models.URLField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('unique_id', models.CharField(blank=True, help_text='D4WEE unique ID', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.AddField(
            model_name='registration',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='app.student'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('DROPPED', 'Dropped')], default='IN_PROGRESS', max_length=20)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='app.cohort')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='app.course')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='app.registration')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='app.student')),
            ],
            options={
                'verbose_name_plural': 'Enrollments',
                'ordering': ['-enrolled_date'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField(help_text='Week number (1-12)')),
                ('date', models.DateField(help_text='Date of attendance')),
                ('learnings', models.TextField(blank=True, help_text='What have you learned this week?')),
                ('assignments_completed', models.CharField(blank=True, help_text='How many assignments completed this week?', max_length=255)),
                ('challenges', models.TextField(blank=True, help_text='Any challenges or roadblocks?')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='app.cohort')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='app.student')),
            ],
            options={
                'ordering': ['-date', 'student__full_name'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_id', models.CharField(max_length=255, unique=True)),
                ('state', models.CharField(choices=[('NEW', 'New'), ('CREATED', 'Created'), ('TURNED_IN', 'Turned In'), ('RETURNED', 'Returned'), ('RECLAIMED_BY_STUDENT', 'Reclaimed by Student')], max_length=50)),
                ('late', models.BooleanField(default=False)),
                ('assigned_grade', models.FloatField(blank=True, null=True)),
                ('draft_grade', models.FloatField(blank=True, null=True)),
                ('creation_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='app.assignment')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='app.enrollment')),
            ],
            options={
                'ordering': ['-update_time'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='IN_PROGRESS', max_length=50)),
                ('courses_synced', models.IntegerField(default=0)),
                ('students_synced', models.IntegerField(default=0)),
                ('assignments_synced', models.IntegerField(default=0)),
                ('submissions_synced', models.IntegerField(default=0)),
                ('errors', models.TextField(blank=True)),
                ('cohort', models.ForeignKey(blank=True, help_text='Cohort being synced', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.cohort')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['assignment_type'], name='app_assignm_assignm_f17649_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['due_date'], name='app_assignm_due_dat_badcd4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together={('registration', 'certificate_type', 'course')},
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['email'], name='app_student_email_3859bf_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['google_id'], name='app_student_google__b37df4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('student', 'cohort')},
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'course', 'cohort')},
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['date'], name='app_attenda_date_fbaf72_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['week_number'], name='app_attenda_week_nu_826d6c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('student', 'cohort', 'week_number')},
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['state'], name='app_submiss_state_367f6a_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['late'], name='app_submiss_late_cdc51b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('enrollment', 'assignment')},
        ),
    ]
