# Generated by Django 5.2.13 on 2026-05-19 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField(help_text='Week number (1-12)')),
                ('date', models.DateField(help_text='Date of attendance submission')),
                ('hours_spent', models.DecimalField(blank=True, decimal_places=2, help_text='How many hours did you spend learning this week?', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='app.cohort')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='app.student')),
            ],
            options={
                'verbose_name_plural': 'Attendance',
                'ordering': ['-date', 'student__full_name'],
            },
        ),
        migrations.DeleteModel(
            name='AttendanceRecord',
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date'], name='app_attenda_date_9b28e9_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['week_number'], name='app_attenda_week_nu_1371f1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'cohort', 'week_number')},
        ),
    ]
