# Generated by Django 5.2.13 on 2026-05-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_attendance_and_simplify'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='attendance',
            name='app_attenda_week_nu_1371f1_idx',
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'cohort', 'date'], name='app_attenda_student_d31a8f_idx'),
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='week_number',
        ),
    ]
