# Generated by Django 5.2.13 on 2026-05-19 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_week_number_from_attendance'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='attendance',
            name='app_attenda_date_9b28e9_idx',
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'cohort', 'date')},
        ),
    ]
