# Generated by Django 5.2.13 on 2026-05-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_attendance_app_attenda_date_9b28e9_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name', 'section']},
        ),
        migrations.RemoveField(
            model_name='course',
            name='code',
        ),
        migrations.RemoveField(
            model_name='course',
            name='status',
        ),
        migrations.AddField(
            model_name='course',
            name='alternate_link',
            field=models.URLField(blank=True, help_text='Link to course in Google Classroom', max_length=500),
        ),
        migrations.AddField(
            model_name='course',
            name='calendar_id',
            field=models.CharField(blank=True, help_text='Calendar ID', max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='course_group_email',
            field=models.EmailField(blank=True, help_text='Course group email', max_length=254),
        ),
        migrations.AddField(
            model_name='course',
            name='course_state',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived'), ('PROVISIONED', 'Provisioned'), ('DECLINED', 'Declined'), ('SUSPENDED', 'Suspended')], default='ACTIVE', help_text='Course state in Google Classroom', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='description_heading',
            field=models.CharField(blank=True, help_text='Short description heading', max_length=500),
        ),
        migrations.AddField(
            model_name='course',
            name='enrollment_code',
            field=models.CharField(blank=True, help_text='Enrollment code for students', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='google_creation_time',
            field=models.DateTimeField(blank=True, help_text='When course was created in Google Classroom', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='google_update_time',
            field=models.DateTimeField(blank=True, help_text='When course was last updated in Google Classroom', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='guardians_enabled',
            field=models.BooleanField(default=False, help_text='Are guardians enabled'),
        ),
        migrations.AddField(
            model_name='course',
            name='owner_id',
            field=models.CharField(blank=True, help_text='Google user ID of owner', max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='room',
            field=models.CharField(blank=True, help_text='Classroom room location', max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='section',
            field=models.CharField(blank=True, help_text='Course section', max_length=500),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_group_email',
            field=models.EmailField(blank=True, help_text='Teacher group email', max_length=254),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, help_text='Full course description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='google_id',
            field=models.CharField(default=1, help_text='Google Classroom course ID', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text='Course name', max_length=500),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['google_id'], name='app_course_google__0d6e44_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_state'], name='app_course_course__e38ddb_idx'),
        ),
    ]
