# Generated by Django 5.2.13 on 2026-05-23 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_course_options_remove_course_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='profile_photo',
        ),
        migrations.AddField(
            model_name='student',
            name='family_name',
            field=models.CharField(blank=True, help_text='Family/last name', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='given_name',
            field=models.CharField(blank=True, help_text='Given/first name', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='is_pilot_student',
            field=models.BooleanField(default=False, help_text='Student from PILOT cohort (legacy data)'),
        ),
        migrations.AddField(
            model_name='student',
            name='photo_url',
            field=models.URLField(blank=True, help_text='Profile photo URL from Google', max_length=500),
        ),
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.CharField(blank=True, help_text='City (local data)', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(help_text='Email address from Google profile', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(help_text='Full name from Google profile', max_length=500),
        ),
        migrations.AlterField(
            model_name='student',
            name='google_id',
            field=models.CharField(help_text='Google user ID (userId from Google Classroom)', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='unique_id',
            field=models.CharField(blank=True, help_text='D4WEE unique ID (local data)', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Django user account if student has logged in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
