# Generated by Django 5.2.13 on 2026-05-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_student_profile_photo_student_family_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='topic',
        ),
        migrations.AddField(
            model_name='assignment',
            name='alternate_link',
            field=models.URLField(blank=True, help_text='Link to assignment in Google Classroom', max_length=500),
        ),
        migrations.AddField(
            model_name='assignment',
            name='google_creation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='google_update_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='topic_id',
            field=models.CharField(blank=True, help_text='Google Classroom topic ID', max_length=255),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assignment_type',
            field=models.CharField(choices=[('PRE_TEST', 'Pre-Test'), ('POST_TEST', 'Post-Test'), ('ASSIGNMENT', 'Assignment'), ('QUIZ', 'Quiz')], default='ASSIGNMENT', help_text='Explicit categorization for tracking (PRE_TEST, POST_TEST, etc.)', max_length=20),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(blank=True, help_text='Combined dueDate + dueTime', null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='google_id',
            field=models.CharField(help_text='Google Classroom coursework ID', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='state',
            field=models.CharField(choices=[('PUBLISHED', 'Published'), ('DRAFT', 'Draft'), ('DELETED', 'Deleted')], default='PUBLISHED', max_length=50),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
