# Generated by Django 5.2.13 on 2026-05-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_assignment_topic_assignment_alternate_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-google_update_time', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='submission',
            name='creation_time',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='update_time',
        ),
        migrations.AddField(
            model_name='submission',
            name='alternate_link',
            field=models.URLField(blank=True, help_text='Link to submission in Google Classroom', max_length=500),
        ),
        migrations.AddField(
            model_name='submission',
            name='google_creation_time',
            field=models.DateTimeField(blank=True, help_text='When submission was created', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='google_update_time',
            field=models.DateTimeField(blank=True, help_text='When submission was last updated', null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='assigned_grade',
            field=models.FloatField(blank=True, help_text='Final assigned grade', null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='draft_grade',
            field=models.FloatField(blank=True, help_text='Draft grade before returning', null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='google_id',
            field=models.CharField(help_text='Google Classroom submission ID', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='late',
            field=models.BooleanField(default=False, help_text='Whether submission was late'),
        ),
    ]
