# Generated by Django 5.2.13 on 2026-06-10 11:14

from django.db import migrations


def delete_all_certificates(apps, schema_editor):
    """Delete all existing certificates before schema change"""
    Certificate = apps.get_model('app', 'Certificate')
    count = Certificate.objects.count()
    if count > 0:
        Certificate.objects.all().delete()
        print(f"Deleted {count} existing certificate(s)")


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_submission_options_and_more'),
    ]

    operations = [
        migrations.RunPython(delete_all_certificates, reverse_code=migrations.RunPython.noop),
    ]
