# Generated by Django 5.2.13 on 2026-06-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_certificate_enrollment_refactor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('registration', 'course')},
        ),
        migrations.RemoveField(
            model_name='registration',
            name='completion_date',
        ),
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='cohort',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='student',
        ),
    ]
