# Generated by Django 5.2.13 on 2026-07-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_enrollment_redundant_fks'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceWeekly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_week', models.CharField(help_text='Year and ISO week number in YYYY-WW format', max_length=7)),
                ('cohort_name', models.CharField(help_text='Name of the cohort', max_length=255)),
                ('record_count', models.IntegerField(default=0, help_text='Number of attendance records for this week and cohort')),
                ('total_enrollments', models.IntegerField(default=0, help_text='Total number of students enrolled in the cohort')),
            ],
            options={
                'db_table': 'attendance_weekly',
                'managed': False,
            },
        ),
    ]
