# Generated by Django 5.2.13 on 2026-08-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_attendanceweekly'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('student', models.CharField(max_length=100)),
                ('cohort', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('grade', models.IntegerField()),
            ],
            options={
                'db_table': 'student_grades',
                'managed': False,
            },
        ),
    ]
