# Generated by Django 5.2.13 on 2026-08-21 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_studentgrades'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={},
        ),
        migrations.AlterField(
            model_name='assignment',
            name='alternate_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assignment_type',
            field=models.CharField(choices=[('Pre-Test', 'Pre Test'), ('Post-Test', 'Post Test'), ('Assignment', 'Assignment'), ('Quiz', 'Quiz')], default='Assignment', max_length=20),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='google_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='state',
            field=models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft'), ('Deleted', 'Deleted')], default='Published', max_length=50),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='topic_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='work_type',
            field=models.CharField(choices=[('Assignment', 'Assignment'), ('Short Answer Question', 'Short Answer Question'), ('Multiple Choice Question', 'Multiple Choice Question')], max_length=50),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='hours_spent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='average_grade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='completion_percentage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='is_open_for_registration',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='max_students',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='status',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('Active', 'Active'), ('Closed', 'Closed')], default='Upcoming', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='alternate_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='course',
            name='calendar_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_group_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_state',
            field=models.CharField(choices=[('Active', 'Active'), ('Archived', 'Archived'), ('Provisioned', 'Provisioned'), ('Declined', 'Declined'), ('Suspended', 'Suspended')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='description_heading',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='course',
            name='enrollment_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='google_creation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='google_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='google_update_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='guardians_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='course',
            name='owner_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='room',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='section',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher_group_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Dropped', 'Dropped')], default='In Progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='family_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='student',
            name='given_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='google_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_pilot_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='student',
            name='unique_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submission',
            name='alternate_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='submission',
            name='assigned_grade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='draft_grade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='google_creation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='google_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='google_update_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='late',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='state',
            field=models.CharField(choices=[('New', 'New'), ('Created', 'Created'), ('Turned In', 'Turned In'), ('Returned', 'Returned'), ('Reclaimed by Student', 'Reclaimed By Student')], max_length=50),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='cohort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.cohort'),
        ),
    ]
