# Generated by Django 5.2.13 on 2026-09-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_certificate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assignment_type',
            field=models.CharField(choices=[('PRE_TEST', 'Pre-Test'), ('POST_TEST', 'Post-Test'), ('ASSIGNMENT', 'Assignment'), ('QUIZ', 'Quiz')], default='ASSIGNMENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='state',
            field=models.CharField(choices=[('PUBLISHED', 'Published'), ('DRAFT', 'Draft'), ('DELETED', 'Deleted')], default='PUBLISHED', max_length=50),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='work_type',
            field=models.CharField(choices=[('ASSIGNMENT', 'Assignment'), ('SHORT_ANSWER_QUESTION', 'Short Answer Question'), ('MULTIPLE_CHOICE_QUESTION', 'Multiple Choice Question')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='status',
            field=models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='UPCOMING', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_state',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived'), ('PROVISIONED', 'Provisioned'), ('DECLINED', 'Declined'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('DROPPED', 'Dropped')], default='IN_PROGRESS', max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='submission',
            name='state',
            field=models.CharField(choices=[('NEW', 'New'), ('CREATED', 'Created'), ('TURNED_IN', 'Turned In'), ('RETURNED', 'Returned'), ('RECLAIMED_BY_STUDENT', 'Reclaimed by Student')], max_length=50),
        ),
    ]
