# Generated by Django 5.2.13 on 2026-09-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_course_is_available_alter_assignment_assignment_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('student', models.CharField(max_length=100)),
                ('cohort', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('grade', models.FloatField()),
                ('completion', models.FloatField()),
                ('attendance', models.FloatField()),
            ],
            options={
                'db_table': 'student_report',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='StudentGrades',
        ),
    ]
